sudo: required
language: python
python:
- '3.5'
cache: pip
services:
- docker
before_install:
# https://docs.travis-ci.com/user/encrypting-files/
# travis encrypting file only allow one file
- openssl aes-256-cbc -K $encrypted_2e3704f31d08_key -iv $encrypted_2e3704f31d08_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- pip install -U pip
- pip install wheel
- mv .dockercfg ~
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
install:
- pip wheel -r requirements.txt
- pip install -r requirements.txt
script:
- cd src
- python manage.py test
- cd $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master
