language: python
cache: pip
services:
- docker
install:
- pip install -r ./requirements.txt -U
- pip install docker-py docker-compose
script:
- cd src
- py.test --cov=./
- flake8 ./
- cd $TRAVIS_BUILD_DIR
before_deploy:
- curl -s https://raw.githubusercontent.com/gliacloud/deploy/master/src/deploy.py
  > deploy.py && chmod +x deploy.py
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.py"
  on:
    branch: master
