sudo: required
language: python
python:
- '3.5'
cache: pip
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2e3704f31d08_key -iv $encrypted_2e3704f31d08_iv
  -in swarm-master.tar.gz.enc -out swarm-master.tar.gz -d
- tar zxvf swarm-master.tar.gz && rm swarm-master.tar.gz
- echo "make deploy" > deploy.sh && chmod +x deploy.sh
- pip install -U pip
- pip install wheel
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
install:
- pip wheel -r requirements.txt
- pip install -r requirements.txt
script:
- cd src && py.test --cov=./
- cd $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master
