sudo: required
language: python
python:
  - "2.7"

cache: pip
services:
  - docker

before_install:
  - pip install -U pip
  - pip install wheel

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt

script:
  - cd src
  - python manage.py test
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/kube/deploy.sh
  on:
    branch: master
